# BCM2708 Platform Support
snd-soc-bcm2708-objs := bcm2708-pcm.o
snd-soc-bcm2708-i2s-objs := bcm2708-i2s.o
snd-soc-rpi-mbed-objs := rpi-mbed.o

obj-$(CONFIG_SND_BCM2708_SOC) += snd-soc-bcm2708.o
obj-$(CONFIG_SND_BCM2708_SOC_I2S) += snd-soc-bcm2708-i2s.o

# BCM2708 Machine Support
obj-$(CONFIG_SND_BCM2708_SOC_RPI_CODEC_MBED) += snd-soc-rpi-mbed.o
