# BCM2708 Platform Support
snd-soc-bcm2708-objs := bcm2708-pcm.o
snd-soc-bcm2708-i2s-objs := bcm2708-i2s.o
snd-soc-rpi-mbed-objs := rpi-mbed.o
snd-soc-rpi-tda1541a-objs := rpi-tda1541a.o
snd-soc-rpi-proto-objs := rpi-proto.o
snd-soc-rpi-ess9018-objs := rpi-ess9018.o

obj-$(CONFIG_SND_BCM2708_SOC) += snd-soc-bcm2708.o
obj-$(CONFIG_SND_BCM2708_SOC_I2S) += snd-soc-bcm2708-i2s.o

# BCM2708 Machine Support
obj-$(CONFIG_SND_BCM2708_SOC_RPI_CODEC_MBED) += snd-soc-rpi-mbed.o
obj-$(CONFIG_SND_BCM2708_SOC_RPI_CODEC_TDA1541A) += snd-soc-rpi-tda1541a.o
obj-$(CONFIG_SND_BCM2708_SOC_RPI_CODEC_PROTO) += snd-soc-rpi-proto.o
obj-$(CONFIG_SND_BCM2708_SOC_RPI_CODEC_ESS9018) += snd-soc-rpi-ess9018.o
